set(CMAKE_SYSTEM_NAME Linux)
set(CMAKE_SYSTEM_VERSION 1)
set(CMAKE_SYSTEM_PROCESSOR x86_64)

set(CMAKE_FIND_LIBRARY_PREFIXES "lib")
set(CMAKE_FIND_LIBRARY_SUFFIXES ".a" ".so")

set(CUSTOM_COMPILE_OPTIONS -fPIC -Wall -fms-extensions -Wno-write-strings -Wno-format-security -Wno-unknown-pragmas -pthread)
if(CMAKE_BUILD_TYPE STREQUAL "Debug")
    list(APPEND CUSTOM_COMPILE_OPTIONS -O0 -g3 -ggdb -ggdb3 -gdwarf-2 -D_DEBUG_=1)
else()
    list(APPEND CUSTOM_COMPILE_OPTIONS -O3 -DNDEBUG)
endif()
string(REPLACE ";" " " CMAKE_CXX_FLAGS "${CUSTOM_COMPILE_OPTIONS}")
string(REPLACE ";" " " CMAKE_C_FLAGS "${CUSTOM_COMPILE_OPTIONS}")

add_definitions(-DLINUX -Dx86_64="x86_64" -DTARGET_NUM_CORES=1 -DTARGET_ARCH=64 -DARCH_64)
if(CMAKE_BUILD_TYPE STREQUAL "Release")
    add_definitions(-DTARGET_BUILD=1)
elseif(CMAKE_BUILD_TYPE STREQUAL "Debug")
    add_definitions(-DTARGET_BUILD=2)
else()
    add_definitions(-DTARGET_BUILD=1)
endif()
